//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAsp.Redis
{
    
    
    /// <summary>
    /// The RedisSection Configuration Section.
    /// </summary>
    public partial class RedisSection : global::System.Configuration.ConfigurationSection
    {
        
        #region Singleton Instance
        /// <summary>
        /// The XML name of the RedisSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string RedisSectionSectionName = "redisSection";
        
        /// <summary>
        /// The XML path of the RedisSection Configuration Section.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string RedisSectionSectionPath = "redisSection";
        
        /// <summary>
        /// Gets the RedisSection instance.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public static global::UAsp.Redis.RedisSection Instance
        {
            get
            {
                return ((global::UAsp.Redis.RedisSection)(global::System.Configuration.ConfigurationManager.GetSection(global::UAsp.Redis.RedisSection.RedisSectionSectionPath)));
            }
        }
        #endregion
        
        #region Xmlns Property
        /// <summary>
        /// The XML name of the <see cref="Xmlns"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string XmlnsPropertyName = "xmlns";
        
        /// <summary>
        /// Gets the XML namespace of this Configuration Section.
        /// </summary>
        /// <remarks>
        /// This property makes sure that if the configuration file contains the XML namespace,
        /// the parser doesn't throw an exception because it encounters the unknown "xmlns" attribute.
        /// </remarks>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.RedisSection.XmlnsPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public string Xmlns
        {
            get
            {
                return ((string)(base[global::UAsp.Redis.RedisSection.XmlnsPropertyName]));
            }
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Db Property
        /// <summary>
        /// The XML name of the <see cref="Db"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string DbPropertyName = "db";
        
        /// <summary>
        /// Gets or sets the Db.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Db.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.RedisSection.DbPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int Db
        {
            get
            {
                return ((int)(base[global::UAsp.Redis.RedisSection.DbPropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.RedisSection.DbPropertyName] = value;
            }
        }
        #endregion
        
        #region Password Property
        /// <summary>
        /// The XML name of the <see cref="Password"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string PasswordPropertyName = "password";
        
        /// <summary>
        /// Gets or sets the Password.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Password.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.RedisSection.PasswordPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual string Password
        {
            get
            {
                return ((string)(base[global::UAsp.Redis.RedisSection.PasswordPropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.RedisSection.PasswordPropertyName] = value;
            }
        }
        #endregion
        
        #region Cluster Property
        /// <summary>
        /// The XML name of the <see cref="Cluster"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string ClusterPropertyName = "cluster";
        
        /// <summary>
        /// Gets or sets the Cluster.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Cluster.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.RedisSection.ClusterPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual bool Cluster
        {
            get
            {
                return ((bool)(base[global::UAsp.Redis.RedisSection.ClusterPropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.RedisSection.ClusterPropertyName] = value;
            }
        }
        #endregion
        
        #region Write Property
        /// <summary>
        /// The XML name of the <see cref="Write"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string WritePropertyName = "write";
        
        /// <summary>
        /// Gets or sets the Write.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Write.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.RedisSection.WritePropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::UAsp.Redis.ItemCollection Write
        {
            get
            {
                return ((global::UAsp.Redis.ItemCollection)(base[global::UAsp.Redis.RedisSection.WritePropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.RedisSection.WritePropertyName] = value;
            }
        }
        #endregion
        
        #region Read Property
        /// <summary>
        /// The XML name of the <see cref="Read"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string ReadPropertyName = "read";
        
        /// <summary>
        /// Gets or sets the Read.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Read.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.RedisSection.ReadPropertyName, IsRequired=true, IsKey=false, IsDefaultCollection=false)]
        public virtual global::UAsp.Redis.ItemCollection Read
        {
            get
            {
                return ((global::UAsp.Redis.ItemCollection)(base[global::UAsp.Redis.RedisSection.ReadPropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.RedisSection.ReadPropertyName] = value;
            }
        }
        #endregion
    }
}
namespace UAsp.Redis
{
    
    
    /// <summary>
    /// A collection of Host instances.
    /// </summary>
    [global::System.Configuration.ConfigurationCollectionAttribute(typeof(global::UAsp.Redis.Host), CollectionType=global::System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate, AddItemName="add", RemoveItemName="remove", ClearItemsName="clear")]
    public partial class ItemCollection : global::System.Configuration.ConfigurationElementCollection
    {
        
        #region Constants
        /// <summary>
        /// The XML name of the individual <see cref="global::UAsp.Redis.Host"/> instances in this collection.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string HostPropertyName = "hostItem";
        #endregion
        
        #region Overrides
        /// <summary>
        /// Gets the type of the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <returns>The <see cref="global::System.Configuration.ConfigurationElementCollectionType"/> of this collection.</returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override global::System.Configuration.ConfigurationElementCollectionType CollectionType
        {
            get
            {
                return global::System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate;
            }
        }
        
        /// <summary>
        /// Gets the name used to identify this collection of elements
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        protected override string ElementName
        {
            get
            {
                return global::UAsp.Redis.ItemCollection.HostPropertyName;
            }
        }
        
        /// <summary>
        /// Indicates whether the specified <see cref="global::System.Configuration.ConfigurationElement"/> exists in the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="elementName">The name of the element to verify.</param>
        /// <returns>
        /// <see langword="true"/> if the element exists in the collection; otherwise, <see langword="false"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        protected override bool IsElementName(string elementName)
        {
            return (elementName == global::UAsp.Redis.ItemCollection.HostPropertyName);
        }
        
        /// <summary>
        /// Gets the element key for the specified configuration element.
        /// </summary>
        /// <param name="element">The <see cref="global::System.Configuration.ConfigurationElement"/> to return the key for.</param>
        /// <returns>
        /// An <see cref="object"/> that acts as the key for the specified <see cref="global::System.Configuration.ConfigurationElement"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        protected override object GetElementKey(global::System.Configuration.ConfigurationElement element)
        {
            return element.GetHashCode();
        }
        
        /// <summary>
        /// Creates a new <see cref="global::UAsp.Redis.Host"/>.
        /// </summary>
        /// <returns>
        /// A new <see cref="global::UAsp.Redis.Host"/>.
        /// </returns>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        protected override global::System.Configuration.ConfigurationElement CreateNewElement()
        {
            return new global::UAsp.Redis.Host();
        }
        #endregion
        
        #region Indexer
        /// <summary>
        /// Gets the <see cref="global::UAsp.Redis.Host"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::UAsp.Redis.Host"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public global::UAsp.Redis.Host this[int index]
        {
            get
            {
                return ((global::UAsp.Redis.Host)(base.BaseGet(index)));
            }
        }
        #endregion
        
        #region Add
        /// <summary>
        /// Adds the specified <see cref="global::UAsp.Redis.Host"/> to the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="hostItem">The <see cref="global::UAsp.Redis.Host"/> to add.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public void Add(global::UAsp.Redis.Host hostItem)
        {
            base.BaseAdd(hostItem);
        }
        #endregion
        
        #region Remove
        /// <summary>
        /// Removes the specified <see cref="global::UAsp.Redis.Host"/> from the <see cref="global::System.Configuration.ConfigurationElementCollection"/>.
        /// </summary>
        /// <param name="hostItem">The <see cref="global::UAsp.Redis.Host"/> to remove.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public void Remove(global::UAsp.Redis.Host hostItem)
        {
            base.BaseRemove(this.GetElementKey(hostItem));
        }
        #endregion
        
        #region GetItem
        /// <summary>
        /// Gets the <see cref="global::UAsp.Redis.Host"/> at the specified index.
        /// </summary>
        /// <param name="index">The index of the <see cref="global::UAsp.Redis.Host"/> to retrieve.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public global::UAsp.Redis.Host GetItemAt(int index)
        {
            return ((global::UAsp.Redis.Host)(base.BaseGet(index)));
        }
        #endregion
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
    }
}
namespace UAsp.Redis
{
    
    
    /// <summary>
    /// The Host Configuration Element.
    /// </summary>
    public partial class Host : global::System.Configuration.ConfigurationElement
    {
        
        #region IsReadOnly override
        /// <summary>
        /// Gets a value indicating whether the element is read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        public override bool IsReadOnly()
        {
            return false;
        }
        #endregion
        
        #region Ip Property
        /// <summary>
        /// The XML name of the <see cref="Ip"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string IpPropertyName = "ip";
        
        /// <summary>
        /// Gets or sets the Ip.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Ip.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.Host.IpPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=true)]
        public virtual string Ip
        {
            get
            {
                return ((string)(base[global::UAsp.Redis.Host.IpPropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.Host.IpPropertyName] = value;
            }
        }
        #endregion
        
        #region Port Property
        /// <summary>
        /// The XML name of the <see cref="Port"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string PortPropertyName = "port";
        
        /// <summary>
        /// Gets or sets the Port.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Port.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.Host.PortPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int Port
        {
            get
            {
                return ((int)(base[global::UAsp.Redis.Host.PortPropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.Host.PortPropertyName] = value;
            }
        }
        #endregion
        
        #region Pool Property
        /// <summary>
        /// The XML name of the <see cref="Pool"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string PoolPropertyName = "pool";
        
        /// <summary>
        /// Gets or sets the Pool.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Pool.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.Host.PoolPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int Pool
        {
            get
            {
                return ((int)(base[global::UAsp.Redis.Host.PoolPropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.Host.PoolPropertyName] = value;
            }
        }
        #endregion
        
        #region Timeout Property
        /// <summary>
        /// The XML name of the <see cref="Timeout"/> property.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        internal const string TimeoutPropertyName = "timeout";
        
        /// <summary>
        /// Gets or sets the Timeout.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ConfigurationSectionDesigner.CsdFileGenerator", "2.0.1.801")]
        [global::System.ComponentModel.DescriptionAttribute("The Timeout.")]
        [global::System.Configuration.ConfigurationPropertyAttribute(global::UAsp.Redis.Host.TimeoutPropertyName, IsRequired=false, IsKey=false, IsDefaultCollection=false)]
        public virtual int Timeout
        {
            get
            {
                return ((int)(base[global::UAsp.Redis.Host.TimeoutPropertyName]));
            }
            set
            {
                base[global::UAsp.Redis.Host.TimeoutPropertyName] = value;
            }
        }
        #endregion
    }
}
